### ISSUE TITLE
Problem with opensuse

### ISSUE THREAD

**Issue by gabboman** [gwutz/news#13]
Hi, I got to compile the program but I get this problem when I try to launch it on opensuse:

./src/news                                                                                                                          [16:39:39]

(process:20481): Tracker-WARNING **: tracker-backend.vala:211: Falling back to bus backend, the direct backend failed to initialize: Locale mismatch, cannot use direct connection

** (process:20481): CRITICAL **: file /home/gabriel/workspace/news/src/ui/application.vala: line 56: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Tracker1.Miner.RSS was not provided by any .service files (g-dbus-error-quark, 2)

(process:20481): GLib-GIO-CRITICAL **: g_application_run: assertion 'G_IS_APPLICATION (application)' failed

Can this be my system's fault?

**Comment by gwutz** [comment]
seems like opensuse packages all tracker miners independent. Do you have a package in your repository named "tracker-miner-rss"?

**Comment by gabboman** [comment]
Fixed!  thank you!

**Comment by gwutz** [comment]
awesome - if i write instructions to compile it on opensuse i will mention that. So thanks back :)
